import bcryptjs from 'bcryptjs';

type Framework = 'react' | 'nextjs' | 'vue' | 'svelte' | 'angular' | 'solidjs' | 'remix' | 'astro' | 'qwik' | 'sveltekit';
type Category = 'dashboards' | 'ecommerce' | 'landing-pages' | 'ui-kits' | 'saas' | 'portfolio';

interface SeedProduct {
  title: string;
  slug: string;
  description?: string;
  price_usd: number;
  url_live_preview?: string;
  file_url: string;
  framework: Framework[];
  version?: string;
  downloads: number;
  images: string[];
  tags: string[];
  category: Category;
}

interface SeedUser {
  email: string;
  password: string;
  name: string;
  role: 'admin' | 'user';
  id: string;
  emailVerified: boolean;
  createdAt: Date;
  updatedAt: Date;
}

interface SeedData {
  users: SeedUser[];
  categories: string[];
  products: SeedProduct[];
}

export const initialData: SeedData = {
  users: [
    {
      email: 'adrianmarval@gmail.com',
      name: 'Adrian Marval',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
      id: '1',
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'solmairamaza@gmail.com',
      name: 'Solmaira Maza',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
      id: '2',
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],

  categories: ['dashboards', 'ecommerce', 'landing-pages', 'ui-kits', 'saas', 'portfolio'],
  products: [
    {
      title: 'Analytics Insights Dashboard',
      slug: 'analytics-insights-dashboard',
      description:
        'Data visualization dashboard template built with React. Designed to provide a foundation for displaying metrics and data structures.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.27.22 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.27.28 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.27.33 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.27.43 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.27.53 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.00 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.06 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.14 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.23 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.32 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.40 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.28.49 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.29.24 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.29.30 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.29.52 PM.png',
        '/products/Analytics%20Insights%20Dashboard/Screenshot 2026-01-22 at 7.30.16 PM.png',
      ],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Argon Dashboard Chakra PRO',
      slug: 'argon-dashboard-chakra-pro',
      description: 'Admin template integrating Chakra UI with React. Provides a modular structure suitable for dashboard development.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Argon%20Dashboard%20Chakra%20PRO/argon-dashboard-chakra-pro.png'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Argon Dashboard PRO Material-UI-V4',
      slug: 'argon-dashboard-pro-material-ui-v4',
      description:
        'Admin dashboard combining React and Material-UI v4. Includes pre-built layouts to serve as a starting point for project development.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Argon%20Dashboard%20PRO%20Material-UI-V4/argon-dashboard-pro-material-ui-v4.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Argon Dashboard React',
      slug: 'argon-dashboard-react',
      description: 'Admin dashboard for React built with Reactstrap. Features a structured layout system for managing data sets.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Argon%20Dashboard%20React/argon-dashboard-react.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'AstroLaunch UI Pro',
      slug: 'astrolaunch-ui-pro',
      description: 'Landing page and dashboard starter built on Astro. Designed to serve as a core template for modern web layouts.',
      price_usd: 0,
      file_url: '',
      framework: ['astro'],
      downloads: 0,
      images: ['/products/AstroLaunch%20UI%20Pro/astro-launch-ui-pro.jpg'],
      tags: ['astro'],
      category: 'landing-pages',
    },
    {
      title: 'Black Dashboard PRO React',
      slug: 'black-dashboard-pro-react',
      description: 'Dark-themed Bootstrap Admin Dashboard designed for React. Features card-based layouts and structured typography.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Black%20Dashboard%20PRO%20React/black-dashboard-pro-react.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'CRM Web App',
      slug: 'crm-web-app',
      description:
        'CRM solution template layout for React applications. Provides a foundational structure for customer management interfaces.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.18.02 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.18.30 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.18.41 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.18.48 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.18.53 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.19.00 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.19.20 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.19.26 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.19.31 PM.png',
        '/products/CRM%20Web%20App/Screenshot 2026-01-22 at 8.19.37 PM.png',
      ],
      tags: ['react'],
      category: 'saas',
    },
    {
      title: 'Community Forum Platform',
      slug: 'community-forum-platform',
      description:
        'Template layout designed for community forums and discussion boards. Includes visual structures for user profiles and threads.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.00 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.09 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.24 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.30 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.36 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.41 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.47 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.52 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.57.58 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.58.17 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.59.04 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 7.59.50 PM.png',
        '/products/Community%20Forum%20Platform/Screenshot 2026-01-22 at 8.00.10 PM.png',
      ],
      tags: ['react'],
      category: 'saas',
    },
    {
      title: 'Creator Influencer Platform',
      slug: 'creator-influencer-platform',
      description:
        'Dashboard layout designed for content creators and influencers. Provides layout views intended for data and metric visualization.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.02.54 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.03.15 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.03.25 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.03.33 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.03.49 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.04.01 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.15.13 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.15.24 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.15.33 PM.png',
        '/products/Creator%20Influencer%20Platform/Screenshot 2026-01-22 at 8.15.47 PM.png',
      ],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Digital Products Store',
      slug: 'digital-products-store',
      description:
        'E-commerce template layouts focusing on digital goods. Includes base interface designs for product listings and user interactions.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.24.05 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.24.15 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.24.35 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.24.58 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.25.17 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.25.26 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.25.34 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.25.47 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.25.53 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.26.00 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.26.06 PM.png',
        '/products/Digital%20Products%20Store/Screenshot 2026-01-22 at 8.26.14 PM.png',
      ],
      tags: ['react'],
      category: 'ecommerce',
    },
    {
      title: 'Ecommerce General',
      slug: 'ecommerce-general',
      description: 'E-commerce storefront template. Includes structural layouts for product previews and grid-based content organization.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.26.26 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.26.35 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.26.40 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.26.48 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.27.22 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.27.29 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.27.37 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.27.43 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.27.49 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.27.54 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.28.00 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.28.06 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.28.15 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.28.27 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.28.54 PM.png',
        '/products/Ecommerce%20General/Screenshot 2026-01-23 at 12.29.11 PM.png',
      ],
      tags: ['react'],
      category: 'ecommerce',
    },
    {
      title: 'Everest Admin Dashboard',
      slug: 'everest-admin-dashboard',
      description:
        'React admin template focused on layout usability. Provides a starting structure for enterprise and foundational applications.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.13.42 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.20.33 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.21.00 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.21.15 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.21.22 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.21.35 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.21.45 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.21.55 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.22.13 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.22.21 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.22.31 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.22.42 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.23.14 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.23.32 PM.png',
        '/products/Everest%20Admin%20Dashboard/Screenshot 2026-01-22 at 6.23.56 PM.png',
      ],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Light Bootstrap Dashboard PRO React',
      slug: 'light-bootstrap-dashboard-pro-react',
      description: 'Bootstrap admin dashboard layout for React. Serves as a starting point featuring fundamental UI elements.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Light%20Bootstrap%20Dashboard%20PRO%20React/light-bootstrap-dashboard-pro-react.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Marketplace Multivendor',
      slug: 'marketplace-multivendor',
      description:
        'Multivendor marketplace template layout. Provides a structural design meant for displaying multiple stores within a single interface.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: [
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.08.45 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.09.10 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.09.18 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.09.26 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.09.59 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.10.07 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.10.16 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.10.25 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.10.34 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.12.21 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 1.12.42 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.12.37 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.12.43 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.12.51 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.12.58 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.13.05 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.13.13 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.13.23 PM.png',
        '/products/Marketplace%20Multivendor/Screenshot 2026-01-23 at 2.14.26 PM.png',
      ],
      tags: ['react'],
      category: 'ecommerce',
    },
    {
      title: 'Material Dashboard 3 PRO React',
      slug: 'material-dashboard-3-pro-react',
      description:
        'Admin dashboard template incorporating Material Design concepts. Provides a standard layout architecture for development.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Material%20Dashboard%203%20PRO%20React/material-dashboard-pro-react.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Material Dashboard Material-UI v4',
      slug: 'material-dashboard-material-ui-v4',
      description: 'Admin dashboard utilizing Material-UI v4. Provides a base layout applying conventional Material Design principles.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Material%20Dashboard%20Material-UI%20v4/material-dashboard-material-ui-v4.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'NextJS Material Dashboard PRO Material-UI v4',
      slug: 'nextjs-material-dashboard-pro-material-ui-v4',
      description:
        'Next.js admin dashboard utilizing the component style of Material-UI v4. Intended as a starting template for Next.js apps.',
      price_usd: 0,
      file_url: '',
      framework: ['react', 'nextjs'],
      downloads: 0,
      images: ['/products/NextJS%20Material%20Dashboard%20PRO%20Material-UI%20v4/nextjs-material-dashboard-pro-material-ui-v4.jpg'],
      tags: ['nextjs'],
      category: 'dashboards',
    },
    {
      title: 'NextJS Material Tailwind Dashboard PRO',
      slug: 'nextjs-material-tailwind-dashboard-pro',
      description: 'Next.js template integrated with Tailwind CSS. Includes basic layout pages for structural starting points.',
      price_usd: 0,
      file_url: '',
      framework: ['react', 'nextjs'],
      downloads: 0,
      images: ['/products/NextJS%20Material%20Tailwind%20Dashboard%20PRO/material-tailwind-dashboard-nextjs-pro.jpg'],
      tags: ['nextjs'],
      category: 'dashboards',
    },
    {
      title: 'Notus React',
      slug: 'notus-react',
      description:
        'UI Kit and Admin base template for Tailwind CSS and React. Features initial presentation and administrative structures.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Notus%20React/notus-react.jpg'],
      tags: ['react'],
      category: 'ui-kits',
    },
    {
      title: 'Paper Dashboard React',
      slug: 'paper-dashboard-react',
      description: 'Bootstrap admin dashboard layout with soft colors. Serves as a straightforward structural template.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Paper%20Dashboard%20React/paper-dashboard-react.jpg'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Purity UI Dashboard PRO',
      slug: 'purity-ui-dashboard-pro',
      description: 'UI Dashboard layout built with Chakra UI. Uses a glassmorphism style and foundational UI elements.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Purity%20UI%20Dashboard%20PRO/purity-ui-dashboard-pro.png'],
      tags: ['react'],
      category: 'dashboards',
    },
    {
      title: 'Vision UI Dashboard PRO Chakra',
      slug: 'vision-ui-dashboard-pro-chakra',
      description: 'Dark-themed admin dashboard layout built with Chakra UI. Provides a foundational aesthetic for web environments.',
      price_usd: 0,
      file_url: '',
      framework: ['react'],
      downloads: 0,
      images: ['/products/Vision%20UI%20Dashboard%20PRO%20Chakra/vision-ui-dashboard-pro-chakra.png'],
      tags: ['react'],
      category: 'dashboards',
    },
  ],
};
